// add product
export const REQUESTED_ADD_PRODUCT = 'REQUESTED_ADD_PRODUCT';
export const REQUESTED_SUCCEEDED_ADD_PRODUCT =
  'REQUESTED_SUCCEEDED_ADD_PRODUCT';
export const REQUESTED_FAILED_ADD_PRODUCT = 'REQUESTED_FAILED_ADD_PRODUCT';
export const FETCHED_ADD_PRODUCT = 'FETCHED_ADD_PRODUCT';

// show products
export const REQUESTED_PRODUCTS = 'REQUESTED_PRODUCTS';
export const REQUESTED_SUCCEEDED_PRODUCTS = 'REQUESTED_SUCCEEDED_PRODUCTS';
export const REQUESTED_FAILED_PRODUCTS = 'REQUESTED_FAILED_PRODUCTS';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';

// delete product
export const REQUESTED_DELETE_PRODUCTS = 'REQUESTED_DELETE_PRODUCTS';
export const REQUESTED_SUCCEEDED_DELETE_PRODUCTS =
  'REQUESTED_SUCCEEDED_DELETE_PRODUCTS';
export const REQUESTED_FAILED_DELETE_PRODUCTS =
  'REQUESTED_FAILED_DELETE_PRODUCTS';
export const FETCHED_DELETE_PRODUCTS = 'FETCHED_DELETE_PRODUCTS';
