// addProductToBasket
export const REQUESTED_ADD_BASKET_PRODUCT = 'REQUESTED_ADD_BASKET_PRODUCT';
export const REQUESTED_SUCCEEDED_ADD_BASKET_PRODUCT =
  'REQUESTED_SUCCEEDED_ADD_BASKET_PRODUCT';
export const REQUESTED_FAILED_ADD_BASKET_PRODUCT =
  'REQUESTED_FAILED_ADD_BASKET_PRODUCT';
export const FETCHED_ADD_BASKET_PRODUCT = 'FETCHED_ADD_BASKET_PRODUCT';

// getBasketProducts
export const REQUESTED_BASKET_PRODUCTS = 'REQUESTED_BASKET_PRODUCTS';
export const REQUESTED_SUCCEEDED_BASKET_PRODUCTS =
  'REQUESTED_SUCCEEDED_BASKET_PRODUCTS';
export const REQUESTED_FAILED_BASKET_PRODUCTS =
  'REQUESTED_FAILED_BASKET_PRODUCTS';
export const FETCHED_BASKET_PRODUCTS = 'FETCHED_BASKET_PRODUCTS';

// delete BasketProduct
export const REQUESTED_DELETE_BASKET_PRODUCTS =
  'REQUESTED_DELETE_BASKET_PRODUCTS';
export const REQUESTED_SUCCEEDED_DELETE_BASKET_PRODUCTS =
  'REQUESTED_SUCCEEDED_DELETE_BASKET_PRODUCTS';
export const REQUESTED_FAILED_DELETE_BASKET_PRODUCTS =
  'REQUESTED_FAILED_DELETE_BASKET_PRODUCTS';
export const FETCHED_DELETE_BASKET_PRODUCTS = 'FETCHED_DELETE_BASKET_PRODUCTS';
