// login user
export const REQUESTED_LOGIN_USER = 'REQUESTED_LOGIN_USER';
export const REQUESTED_SUCCEEDED_LOGIN_USER = 'REQUESTED_SUCCEEDED_LOGIN_USER';
export const REQUESTED_FAILED_LOGIN_USER = 'REQUESTED_FAILED_LOGIN_USER';
export const FETCHED_LOGIN_USER = 'FETCHED_LOGIN_USER';

// register user
export const REQUESTED_REGISTER_USER = 'REQUESTED_REGISTER_USER';
export const REQUESTED_SUCCEEDED_REGISTER_USER =
  'REQUESTED_SUCCEEDED_REGISTER_USER';
export const REQUESTED_FAILED_REGISTER_USER = 'REQUESTED_FAILED_REGISTER_USER';
export const FETCHED_REGISTER_USER = 'FETCHED_REGISTER_USER';

// show info current User
export const REQUESTED_USER = 'REQUESTED_USER';
export const REQUESTED_SUCCEEDED_USER = 'REQUESTED_SUCCEEDED_USER';
export const REQUESTED_FAILED_USER = 'REQUESTED_FAILED_USER';
export const FETCHED_USER = 'FETCHED_USER';

// delete user
export const REQUESTED_DELETE_USER = 'REQUESTED_DELETE_USER';
export const REQUESTED_SUCCEEDED_DELETE_USER =
  'REQUESTED_DELETE_SUCCEEDED_USER';
export const REQUESTED_FAILED_DELETE_USER = 'REQUESTED_DELETE_FAILED_USER';
export const FETCHED_DELETE_USER = 'FETCHED_DELETE_USER';

// All Users
export const REQUESTED_ALL_USERS = 'REQUESTED_ALL_USERS';
export const REQUESTED_SUCCEEDED_ALL_USERS = 'REQUESTED_SUCCEEDED_ALL_USERS';
export const REQUESTED_FAILED_ALL_USERS = 'REQUESTED_FAILED_ALL_USERS';
export const FETCHED_ALL_USERS = 'FETCHED_ALL_USERS';
